### ISSUE TITLE
launchStore() encountered with LateInitializationError

### ISSUE THREAD

**Issue by ManInTheWind** [Skyost/RateMyApp#132]
i just open myapp and tag the button to launchAppStore
```shell
[log] ERROR LateInitializationError: Field 'doNotOpenAgain' has not been initialized.
      #0      DoNotOpenAgainCondition.saveToPreferences (package:rate_my_app/src/conditions.dart)
      #1      RateMyApp.save (package:rate_my_app/src/core.dart:67)
      <asynchronous suspension>
      #2      RateMyApp.callEvent (package:rate_my_app/src/core.dart:262)
      <asynchronous suspension>
```

**Comment by ManInTheWind** [comment]
sorry about that, after checked my code , its my problem.😜
