### ISSUE TITLE
Unhandled Exception: PlatformException(com.google.android.play.core.internal.aq, Failed to bind to the service., null)

### ISSUE THREAD

**Issue by Skyost** [Skyost/RateMyApp#72]
**Describe the bug**
The error `Unhandled Exception: PlatformException(com.google.android.play.core.internal.aq, Failed to bind to the service., null)` occurs while trying to show a native rate dialog.

**To Reproduce**
Call `showRateDialog` or `showStarRateDialog`.

**Expected behavior**
Shows the (native) rate dialog.

**Smartphone (please complete the following information):**
Android / iOS.

**Additional context**
Stacktrace :

```
I/PlayCore(13766): UID: [10157]  PID: [13766] ReviewService : requestInAppReview (com.bhujmandir.vachanamrut)
I/PlayCore(13766): UID: [10157]  PID: [13766] ReviewService : Initiate binding to the service.
I/PlayCore(13766): UID: [10157]  PID: [13766] ReviewService : Failed to bind to the service.
E/flutter (13766): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(com.google.android.play.core.internal.aq, Failed to bind to the service., null)
E/flutter (13766): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter (13766): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter (13766): <asynchronous suspension>
E/flutter (13766): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (13766): #3      RateMyApp.launchNativeReviewDialog (package:rate_my_app/src/core.dart:106:16)
E/flutter (13766): #4      RateMyApp.showStarRateDialog (package:rate_my_app/src/core.dart:169:13)
E/flutter (13766): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13766): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13766): #7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13766): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13766): #9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13766): #10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13766): #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
E/flutter (13766): #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
E/flutter (13766): #13     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (13766): #14     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (13766): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (13766): #16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter (13766): #17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter (13766): #18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter (13766): #19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter (13766): #20     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter (13766): #21     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (13766): #22     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (13766): #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (13766): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (13766): #25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (13766): #26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (13766): 
```

OP : @PritamSangani.

**Comment by Skyost** [comment]
Should have been fixed in fa1cf79558946a8cd0dc14204a41c738ab242599.
